{% set name = "ossfs" %}
{% set version = "2023.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ossfs-{{ version }}.tar.gz
  sha256: f99eb2d74717d22551b1f32ec9434587962627a816a64536dc47d68470536110

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=6.3.1
  run:
    - aiooss2 >=0.2.7
    - oss2 ==2.18.1
    - fsspec >=2023.9.2
    - python >={{ python_min }}

test:
  imports:
    - ossfs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ossfs/
  summary: ossfs fsspec filesystem for Alibaba Cloud (Aliyun) Object Storage System (OSS)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - karajan1001
    - efiop
